name: ssh command
on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: cdqag/action-configure-ssh-host@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }} 

      - name: Run deploy script via SSH
        run: ssh ${{ steps.ssh.outputs.SERVER }} bash /app/shiori_yonemura/deploy.sh shiori_yonemura

