name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. StagingサーバーにSSH設定
      - name: Configure SSH (Staging)
        uses: cdqag/action-configure-ssh-host@v1
        with:
          name: staging-server
          host: ${{ secrets.DEV_SSH_HOST }}
          port: ${{ secrets.DEV_SSH_PORT }}
          user: ${{ secrets.DEV_SSH_USER }}
          private-key: ${{ secrets.DEV_SSHE_SSH_KEY }}

      # 2. Stagingにデプロイ（deploy.sh 内でCypressテストも実行）
      - name: Deploy and run tests on Staging
        run: ssh staging-server bash /app/shiori_yonemura/deploy.sh shiori_yonemura

      # 3. ProductionサーバーにSSH設定
      - name: Configure SSH (Production)
        uses: cdqag/action-configure-ssh-host@v1
        with:
          name: prod-server
          host: ${{ secrets.PROD_SSH_HOST }}
          port: ${{ secrets.PROD_SSH_PORT }}
          user: ${{ secrets.PROD_SSH_USER }}
          private-key: ${{ secrets.PROD_SSH_KEY }}

      # 4. Stagingテストが成功したらProductionにデプロイ（Dockerコンテナ内で実行）
      - name: Deploy to Production inside Docker
        run: |
          ssh prod-server "docker exec -i app bash /app/shiori_yonemura/deploy.sh shiori_yonemura"
